/**
 * # EmbedPage
 *
 * Push Widget customizer/generator — a tenant styles their own site's
 * "enable notifications" button or popup card (text, colors, corner
 * radius) and gets back copy-pasteable code, pre-filled with this
 * tenant's real credentials (VAPID public key, tenant ID, and the most
 * recently minted token — same `store/mintedToken.store` slot
 * `MintTokenCard` writes to, reused here rather than minting a second,
 * separate token).
 *
 * Two prompt modes (`mode`): a plain **button** the visitor clicks, or a
 * **popup** card (in the spirit of a "Sign in with Google" account
 * chooser) that appears on its own and re-appears after
 * `repromptIntervalDays` if dismissed — that interval is baked into the
 * generated code itself (a `localStorage` timestamp compared client-side),
 * not a live backend setting, so it works the same way for the zero-build
 * vanilla embed as for the React component.
 *
 * Two output formats per mode: the vanilla `mio-vapid-subscription.js`
 * embed (any site, no build step) and a `@mio/realtime-sdk-react`
 * component snippet. Both call the same backend endpoint underneath —
 * this page just fills in the styling and the tenant's own values, it
 * doesn't invent a third way to subscribe.
 *
 * A third section below generates a base `sw.js` (service worker) with
 * push + notificationclick handlers already wired up, since Web Push
 * can't be registered without one already deployed at `swUrl`.
 */

import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Download, Wand2 } from 'lucide-react'
import { Button } from '@components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@components/ui/card'
import { Input } from '@components/ui/input'
import { Label } from '@components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@components/ui/select'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@components/ui/tabs'
import { CodeBlock } from '@components/shared/CodeBlock'
import { MintTokenCard } from '@components/shared/MintTokenCard'
import { getVapidKeyAction } from '@actions/vapid/getVapidKey.action'
import { getKeysAction } from '@actions/keys/getKeys.action'
import { isCredentialsExpired } from '@lib/credentialsFile'
import { env } from '@lib/env'
import { useTranslation } from '@lib/i18n'
import { useMintedTokenStore } from '@store/mintedToken.store'
import { downloadBlob } from '@lib/utils'

const RADIUS_PRESETS = [
  { value: 0, label: 'Square' },
  { value: 6, label: 'Subtle' },
  { value: 12, label: 'Rounded' },
  { value: 9999, label: 'Pill' },
]

const POSITION_OPTIONS = ['bottom-right', 'bottom-left', 'top-right', 'top-left'] as const
type PopupPosition = (typeof POSITION_OPTIONS)[number]

const MIO_VAPID_SUBSCRIPTION_CDN =
  'https://cdn.jsdelivr.net/gh/DalesJuvis/realtime-platform@v0.1.11/sdk-wordpress/assets/js/mio-vapid-subscription.min.js'

const SERVICE_WORKER_CODE = `// sw.js — generated by the Mio Push Widget. Deploy this file at the
// \`swUrl\` given to the widget above (default: /sw.js, at your site's
// root so its scope covers the whole origin).
//
// Channels aren't filtered here: which channels a visitor is subscribed
// to is decided once, at registration time (the "Channels" field above)
// — every push this device receives already matches one of them, so this
// file just needs to display whatever payload arrives.

self.addEventListener('push', (event) => {
  const raw = event.data ? event.data.text() : ''
  let title = 'New notification'
  let body = raw
  let url = null

  try {
    const parsed = JSON.parse(raw)
    if (parsed && typeof parsed === 'object') {
      if (typeof parsed.title === 'string') title = parsed.title
      if (typeof parsed.message === 'string') body = parsed.message
      if (typeof parsed.url === 'string' && /^https?:\\/\\//.test(parsed.url)) url = parsed.url
    }
  } catch {
    // Not JSON — show the raw text as-is, same as the notification bell
    // in the tenant dashboard does for plain-text payloads.
  }

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      data: { url },
    }),
  )
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data && event.notification.data.url
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (client.url === (url || '/') && 'focus' in client) return client.focus()
      }
      if (self.clients.openWindow) return self.clients.openWindow(url || '/')
    }),
  )
})
`

export default function EmbedPage() {
  const { t } = useTranslation()
  const credentials = useMintedTokenStore((s) => s.credentials)
  const [vapidPublicKey, setVapidPublicKey] = useState<string | null>(null)
  const [tenantId, setTenantId] = useState<string | null>(null)

  useEffect(() => {
    getVapidKeyAction().then(setVapidPublicKey).catch(() => setVapidPublicKey(null))
    getKeysAction()
      .then((keys) => setTenantId(keys.tenantId))
      .catch(() => setTenantId(null))
  }, [])

  const [mode, setMode] = useState<'button' | 'popup'>('button')
  const [buttonText, setButtonText] = useState('Enable notifications')
  const [bgColor, setBgColor] = useState('#FF5E1A')
  const [textColor, setTextColor] = useState('#FFFFFF')
  const [radius, setRadius] = useState(6)
  const [channels, setChannels] = useState('*')

  const [popupTitle, setPopupTitle] = useState('Enable notifications?')
  const [popupDescription, setPopupDescription] = useState('Get notified about new activity, even when this tab is closed.')
  const [popupConfirmLabel, setPopupConfirmLabel] = useState('Enable')
  const [popupTheme, setPopupTheme] = useState<'light' | 'dark'>('light')
  const [popupPosition, setPopupPosition] = useState<PopupPosition>('bottom-right')
  const [repromptIntervalDays, setRepromptIntervalDays] = useState(3)

  const token = credentials && !isCredentialsExpired(credentials) ? credentials.token : null
  const apiUrl = env.defaultApiUrl
  const channelList = channels
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean)

  const buttonStyle: React.CSSProperties = {
    background: bgColor,
    color: textColor,
    borderRadius: `${radius}px`,
    border: 'none',
    padding: '10px 20px',
    font: 'inherit',
    fontWeight: 500,
    cursor: 'pointer',
  }

  const buttonHtmlCode = `<script src="${MIO_VAPID_SUBSCRIPTION_CDN}"
  data-api-base-url="${apiUrl}"
  data-tenant-id="${tenantId ?? '…'}"
  data-token="${token ?? '…'}"
  data-vapid-public-key="${vapidPublicKey ?? '…'}"
  data-channels="${channels || '*'}"
  data-button="#enable-notifications"
></script>
<button
  id="enable-notifications"
  style="background:${bgColor};color:${textColor};border-radius:${radius}px;border:none;padding:10px 20px;font:inherit;font-weight:500;cursor:pointer;"
>${buttonText}</button>`

  const popupHtmlCode = `<script src="${MIO_VAPID_SUBSCRIPTION_CDN}"
  data-mode="popup"
  data-api-base-url="${apiUrl}"
  data-tenant-id="${tenantId ?? '…'}"
  data-token="${token ?? '…'}"
  data-vapid-public-key="${vapidPublicKey ?? '…'}"
  data-channels="${channels || '*'}"
  data-title="${popupTitle}"
  data-description="${popupDescription}"
  data-confirm-label="${popupConfirmLabel}"
  data-accent-color="${bgColor}"
  data-theme="${popupTheme}"
  data-position="${popupPosition}"
  data-reprompt-interval-days="${repromptIntervalDays}"
></script>`

  const htmlCode = mode === 'popup' ? popupHtmlCode : buttonHtmlCode

  const buttonReactCode = `import { PushPermissionButton } from '@mio/realtime-sdk-react'

<PushPermissionButton
  apiBaseUrl="${apiUrl}"
  token={token}
  tenantId="${tenantId ?? '…'}"
  vapidPublicKey="${vapidPublicKey ?? '…'}"
  channels={[${channelList.map((c) => `'${c}'`).join(', ') || "'*'"}]}
  style={{
    background: '${bgColor}',
    color: '${textColor}',
    borderRadius: ${radius},
    border: 'none',
    padding: '10px 20px',
    fontWeight: 500,
    cursor: 'pointer',
  }}
>
  ${buttonText}
</PushPermissionButton>`

  const popupReactCode = `import { PushPermissionPopup } from '@mio/realtime-sdk-react'

<PushPermissionPopup
  apiBaseUrl={apiUrl}
  token={token}
  tenantId="${tenantId ?? '…'}"
  vapidPublicKey="${vapidPublicKey ?? '…'}"
  channels={[${channelList.map((c) => `'${c}'`).join(', ') || "'*'"}]}
  title="${popupTitle}"
  description="${popupDescription}"
  confirmLabel="${popupConfirmLabel}"
  accentColor="${bgColor}"
  theme="${popupTheme}"
  position="${popupPosition}"
  repromptIntervalDays={${repromptIntervalDays}}
/>`

  const reactCode = mode === 'popup' ? popupReactCode : buttonReactCode

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">{t.embed.pageTitle}</h1>
        <p className="text-sm text-muted-foreground">{t.embed.pageSubtitle}</p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2 lg:items-start">
        <div className="space-y-6">
          <Card className="rounded-sm shadow-none">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-base">
                <Wand2 className="h-4 w-4" />
                {t.embed.customizeTitle}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-1.5">
                <Label>{t.embed.modeLabel}</Label>
                <Select value={mode} onValueChange={(v) => setMode(v as 'button' | 'popup')}>
                  <SelectTrigger className="max-w-xs">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="button">{t.embed.modeButton}</SelectItem>
                    <SelectItem value="popup">{t.embed.modePopup}</SelectItem>
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground">
                  {mode === 'popup' ? t.embed.modePopupHint : t.embed.modeButtonHint}
                </p>
              </div>

              {mode === 'button' && (
                <div className="space-y-1.5">
                  <Label htmlFor="button-text">{t.embed.buttonTextLabel}</Label>
                  <Input id="button-text" value={buttonText} onChange={(e) => setButtonText(e.target.value)} />
                </div>
              )}

              {mode === 'popup' && (
                <>
                  <div className="space-y-1.5">
                    <Label htmlFor="popup-title">{t.embed.popupTitleLabel}</Label>
                    <Input id="popup-title" value={popupTitle} onChange={(e) => setPopupTitle(e.target.value)} />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="popup-description">{t.embed.popupDescriptionLabel}</Label>
                    <Input id="popup-description" value={popupDescription} onChange={(e) => setPopupDescription(e.target.value)} />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="popup-confirm-label">{t.embed.popupConfirmLabelLabel}</Label>
                    <Input id="popup-confirm-label" value={popupConfirmLabel} onChange={(e) => setPopupConfirmLabel(e.target.value)} />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label>{t.embed.popupThemeLabel}</Label>
                      <Select value={popupTheme} onValueChange={(v) => setPopupTheme(v as 'light' | 'dark')}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="light">{t.embed.popupThemeLight}</SelectItem>
                          <SelectItem value="dark">{t.embed.popupThemeDark}</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div className="space-y-1.5">
                      <Label>{t.embed.popupPositionLabel}</Label>
                      <Select value={popupPosition} onValueChange={(v) => setPopupPosition(v as PopupPosition)}>
                        <SelectTrigger>
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {POSITION_OPTIONS.map((p) => (
                            <SelectItem key={p} value={p}>
                              {p}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="reprompt-interval">{t.embed.popupRepromptLabel}</Label>
                    <Input
                      id="reprompt-interval"
                      type="number"
                      min={0}
                      value={repromptIntervalDays}
                      onChange={(e) => setRepromptIntervalDays(Math.max(0, Number(e.target.value) || 0))}
                      className="max-w-xs"
                    />
                    <p className="text-xs text-muted-foreground">{t.embed.popupRepromptHint}</p>
                  </div>
                </>
              )}

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label htmlFor="bg-color">{mode === 'popup' ? t.embed.accentColorLabel : t.embed.backgroundColorLabel}</Label>
                  <div className="flex items-center gap-2">
                    <input
                      id="bg-color"
                      type="color"
                      value={bgColor}
                      onChange={(e) => setBgColor(e.target.value)}
                      className="h-9 w-9 shrink-0 cursor-pointer rounded-md border border-input bg-transparent p-1"
                    />
                    <Input value={bgColor} onChange={(e) => setBgColor(e.target.value)} className="font-mono text-xs" />
                  </div>
                </div>
                {mode === 'button' && (
                  <div className="space-y-1.5">
                    <Label htmlFor="text-color">{t.embed.textColorLabel}</Label>
                    <div className="flex items-center gap-2">
                      <input
                        id="text-color"
                        type="color"
                        value={textColor}
                        onChange={(e) => setTextColor(e.target.value)}
                        className="h-9 w-9 shrink-0 cursor-pointer rounded-md border border-input bg-transparent p-1"
                      />
                      <Input value={textColor} onChange={(e) => setTextColor(e.target.value)} className="font-mono text-xs" />
                    </div>
                  </div>
                )}
              </div>

              {mode === 'button' && (
                <div className="space-y-1.5">
                  <Label>{t.embed.cornerRadiusLabel}</Label>
                  <Select value={String(radius)} onValueChange={(v) => setRadius(Number(v))}>
                    <SelectTrigger className="max-w-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {RADIUS_PRESETS.map((p) => (
                        <SelectItem key={p.value} value={String(p.value)}>
                          {p.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              <div className="space-y-1.5">
                <Label htmlFor="channels">{t.embed.channelsLabel}</Label>
                <Input id="channels" value={channels} onChange={(e) => setChannels(e.target.value)} placeholder="*" />
                <p className="text-xs text-muted-foreground">{t.embed.channelsHint}</p>
              </div>
            </CardContent>
          </Card>

          <MintTokenCard />
        </div>

        <div className="space-y-6 lg:sticky lg:top-8 lg:self-start">
          <Card className="rounded-sm shadow-none">
            <CardHeader>
              <CardTitle className="text-base">{t.embed.previewTitle}</CardTitle>
              <CardDescription>{t.embed.previewNote}</CardDescription>
            </CardHeader>
            <CardContent>
              {mode === 'button' ? (
                <div className="flex items-center justify-center rounded-md border border-dashed border-border bg-muted/30 p-10">
                  <button type="button" style={buttonStyle} onClick={() => toast.info(t.embed.previewClickToast)}>
                    {buttonText || t.embed.buttonTextLabel}
                  </button>
                </div>
              ) : (
                <div className="flex items-center justify-center rounded-md border border-dashed border-border bg-muted/30 p-10">
                  <div
                    className="w-72 rounded-xl border p-4 shadow-lg"
                    style={{
                      background: popupTheme === 'dark' ? '#1e1f26' : '#ffffff',
                      color: popupTheme === 'dark' ? '#f3f3f5' : '#1a1a1a',
                      borderColor: popupTheme === 'dark' ? '#33343d' : '#e0e0e0',
                    }}
                  >
                    <p className="text-sm font-semibold">{popupTitle || t.embed.popupTitleLabel}</p>
                    <p className="mt-1 text-xs opacity-70">{popupDescription}</p>
                    <button
                      type="button"
                      onClick={() => toast.info(t.embed.previewClickToast)}
                      className="mt-3 w-full rounded-full px-4 py-2 text-sm font-medium text-white"
                      style={{ background: bgColor }}
                    >
                      {popupConfirmLabel || t.embed.popupConfirmLabelLabel}
                    </button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="rounded-sm shadow-none">
            <CardHeader>
              <CardTitle className="text-base">{t.embed.codeTitle}</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {!vapidPublicKey && <p className="text-sm text-destructive">{t.embed.noVapidKey}</p>}
              {vapidPublicKey && !token && <p className="text-sm text-amber-600 dark:text-amber-400">{t.embed.noToken}</p>}

              <Tabs defaultValue="html">
                <TabsList>
                  <TabsTrigger value="html">{t.embed.formatVanilla}</TabsTrigger>
                  <TabsTrigger value="react">{t.embed.formatReact}</TabsTrigger>
                </TabsList>
                <TabsContent value="html" className="mt-3">
                  <CodeBlock code={htmlCode} label={t.embed.vanillaCodeLabel} language="markup" />
                </TabsContent>
                <TabsContent value="react" className="mt-3">
                  <CodeBlock code={reactCode} label={t.embed.reactCodeLabel} language="typescript" />
                </TabsContent>
              </Tabs>

              {token && <p className="text-xs text-muted-foreground">{t.embed.tokenExpiresNote}</p>}
            </CardContent>
          </Card>

          <Card className="rounded-sm shadow-none">
            <CardHeader>
              <CardTitle className="text-base">{t.embed.swTitle}</CardTitle>
              <CardDescription>{t.embed.swNote}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <CodeBlock code={SERVICE_WORKER_CODE} label="sw.js" language="typescript" />
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => {
                  downloadBlob(new Blob([SERVICE_WORKER_CODE], { type: 'text/javascript' }), 'sw.js')
                  toast.success(t.embed.swDownloaded)
                }}
              >
                <Download className="mr-2 h-4 w-4" />
                {t.embed.swDownloadButton}
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
